dist: trusty

language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  

services:
  - docker

matrix:
  include:
    - if: type = push
      env: PROFILES=""
    - if: type = cron
      env: PROFILES=",mutation-testing"

before_install:
- sudo apt-get install -y tightvncserver
- sudo apt-get install -y expect
      
script:
  - git fetch --unshallow origin develop:develop
  - ./execute-on-vnc.sh mvn -f com.riccardomalavolti.apps.todolist/todolist-jacoco-report-aggregator/pom.xml -Pjacoco,code-analysis$MUTATION clean verify
