language: java

jdk: openjdk8

install: true

secure: "qYvqEK/JIxJEBSnwBUxYewa3N/a4trcXI45FSA3lwcDPzx5KJ1dnatoDEXdMAS/GrwotsF9PubesgraGmLiOoaQHGCJPQ8kY+HDlFffjNFAdV76LZVqdXN0aIUaen2hSrDsRM7qhOvDvyUoD58OVvnkzKSoK+G0MxfSVxtqw82da6UfM1e1rXLnxOGkDLqVWHtV75QE/vhHTzcsQLKaRkS1tND/2P/EBwR+zW9DUZDcwQ7dnQ9HQ72+DtGupTa3MU66pG+UnD+kpV9njWxtKJOlg5+WIiE0XrP2YQo6oP5SJf3gavLV5ADalw+gDPWBpnXYj5iqoMHtdUqhmJsXOoiW58LAdBi0S8slJVjOAklKxOc/Kb678hEk7KY6+GZyXmtfUsNyrsty8a0fDZzDHLTQevCP2aYuEl8UBo92b2ZDQTHhu6VMgS/5LhbjykX0VvUmgzPapV4+KknbaBmh1Lk/33IrXhhWVaF6t5fO/uDePpyT0OYn0eSLXPKEaSr6LqDPCuc4XgCkYiSzRzAdD+uf1A4tOXycSDveF+J4PVQJa4h+J2C1er5WcuM4sPKelKjdDd2wH0uS+fAymCk6uFLT9OgN5e69B4XaUu4ko4sImUkgFTO37tQnkDky5+O0p5RXJkTIvG86cWAcRLk7Ogqy8d4KZTGqEuqVKpjdwV6A="
secure: "N5KzaJU34rE37cO9NqZzt6H70OxkoquidwrkTXRlaIDcRKlYTUX4LTKY+RTgf7IFXnqASdKYZpj4D3GGHGLX/fRUjSn6VbsFflnkNkEcChQC13M4bWPkTrYovrqSQYx5JGS0xM8vIevdMSN0231a89E+AwM6zXfzFPoSuIPMOTSXnqdRoPdXLsIeZggwqyWpHDjSc9n7bWdoqNU3P8Alqa1Rg9woTmu46DxlyqCPvJW8wzeAvS/V0PdQ7nYRrNlvfaDTXD6qO7nfqnk/KkP+umBzZRS/axlDY+rzXp7Kpc15LltljywUkIimol07NtQFVhDQ2sMHk1a2Cqmx66VDt2WRKTs7Phw4UoV6SeLInJ/sAqDTv+aNuk550XtwW8V2Rmq2kpgoVGYTDh5Cp9Bu917sHoUEqL/LIU9B27o9/S5GLd7/SQSARsRTa74VDbk7VpPjK+TNv6bbk5EZ8pn/hgFN0ra2G3s6yJAWTWZXFLTK7dDq7p92X4Wgyt3eCrcILOtYa5BX/kFhdpWddV6bTUSNR4iaPXdaK5kg/yC1nA6IFE5Ir3DgZHA0cLvgi/UUPsXaAfnV5UqVgg78d4UpNqxybnJOt158KWKJ9hgnOgyx7u/QXfdHqelVEceUtYCr5YHW4WzPbtg7sAy+QD3Wt5Q4T4xFxnKGtiX6RgBywqU="


cache:
    directories:
        - $HOME/.m2

script:
    - mvn -f com.riccardomalavolti.apps.todolist/pom.xml clean verify -Pjacoco jacoco:report coveralls:report
