dist: xenial

language: java
jdk: openjdk8
install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  

services:
  - docker

matrix:
  include:
    - if: type = push
      env: PROFILES=""
    - if: type = cron
      env: PROFILES=",mutation-testing"

before_install:
- sudo apt-get install -y tightvncserver
- sudo apt-get install -y expect
      
script:
- ./execute-on-vnc.sh mvn -f com.riccardomalavolti.apps.todolist/pom.xml -Pjacoco,code-analysis$MUTATION clean verify
