language: java

jdk: openjdk8

install: true

cache:
    directories:
        - $HOME/.m2
	- $HOME/.sonar/cache

matrix:
    include:
	- if: type = cron
	    env: PROFILES="jacoco,mutation-testing"
	- if: type = push
	    env: PROFILES="jacoco"

script:
    - mvn -f com.riccardomalavolti.apps.todolist/pom.xml clean test verify $PROFILES jacoco:report coveralls:report sonar:sonar
