language: java
jdk: openjdk8
install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  
env:
  global:
  - secure: qeQNir5Q4W1bHg2k4lofkWCRNZHYVuao+2ChepGQMcnYRiNsZmPrW8heRFKLinxDyExGSRRpFW20IyC1yQHyIe79ruwYUcfH300I/uuzaBlbkPJF4E+BuJ90LWmkMLlODrHNT1Z+nMLYfr7zVA/M+gEGujDJNsbZppTD0STgUSrzkVMIsDbiJOQN+Cv4h89xbgWUiW5Wk0et+NHDDnOVyUJgs64M3GqM7EnocWxopJdSV++gM9RS0jpitsDqsSy0tOs26hacUUDspOmw9FzXpjDF7WfrLNPmzCiBnAAomu7Rost5mC5787urnqgrXxsriZgRMh9p5vGtzXEcCELjlsAQJGQUhbWUbusF9oeY6AnK8fNaRgZKTJmDkyEzjattXR4URde2dpO3eDhevfcQfbO0iqZ7R40AqZ08LH86PcGrrVheVcWCxZXw9zbPejibjgLUXrBvO38lCRQpbZS4Yj3vQJz3ZeUzZhQ1qHePIJceS9e66Z37nb+IP6sXhN/IqGpoPOtb1tuH6n/eUTRw6mNG8e3d1FbTky0nReqFOkhv5NYIF2FPDtiP1YuRAMiKdVuaBxvJjt1D56kJQzNBTAUtZ90Ea4LUYJPL5nMWSbv9RMM9tFtxeUDpKy/zgKBiLX3/LQBeITZlDTSd52BmoUyp6XzWEm5yorRdosC2I5w=
  - secure: fQjPth5B1CTBomEoEk4Yt5T8RY1kxhmUbM2ZC0jxfoZWG9LRZr1Av5W62vY60SctExibXz/eTCO64IW4b3XU8YPN2esyU35Wy2EMqGcgDpdMh55bKLGNvYAMxQFACY7FddTk2vaWqS6QDtg9swWp49PTXgJV7CI76C0rpt1c5oBt1wvwe1CoYd4oujpkrAaYwS4lbIUZj8azjWnGzivnWqzyDuWOyzISsGTPV4lSxl5lUN2VlMqd1h8fq9WosW00CYOfk00yDUwNfuwunUexX8tYW15xsRK1ZWFsr973uqI/WPyMb0NTx7wOVVZxQvlIKDHXYw1euOsQoK1sqauBNOpzLmu4Q1yJn7Pm7jBnvZBnv+k0a93+Vl6AVJCdaV0S8Ur1ismdNBV49kOwooPAPFfa58jKDm7MR2PgIBei1BFAFCX/uM3Y9gMnNmoIiNAFM4r7LHJ/VeJCBj7qkkM4KvsBIPBaethzB26VbTtAUzstkvh25WGApxS0GJX+kSVb9tCRKeKkhh0D0ZlCpaO9OPTRYWik36jLRQhP/9kXYBbfT6OtxGJa82UjgHFlPtqhGTttAfutb3G2MitDMw3C4sHqI4GbdYD3qgpJv91iYK8UQu3tBjCiW8zeqX5/ge8jZcyteL9B/kk3DmwyiiGlHM5DQQXHp1ZeJG2NaJegd7E=
  - secure: CnMeZ1GNGH+7XayQ/eSuYa1UU+8PfPGHd8dt+7FYAN4jEe2Xx/iTm58QpO7yooPJo4cPcO6+zROT+b6SIZNnjpp/TMIt65lxt2Vkp6W9C4ZJBK89Kdj3xKcZYMeCACvqLaXqUjbbsukz/foXFL9NWWLpLHhmgsU5kt4McIa/SieiNOViNpfMwPHznmyYPKbXoiRNkecvo8nNnt+MPqhxX1puWWzN3YsZNDCbx6Z5DhfipeBqH27x3YisStT2Srl5yxQVtr3zmQabDW+9oHbhKNcyXmYzzDGzWnu9DL3edPDT1QPzbSLkF+ktC9ps66eJJv5YnlMuv9WnbF3i4u23HRW2SWGCSUymXHCIOpgfuE84t0RVlkoZYWxNgpb9/nRoqmtcQtELvpU+DgIlu+Zb6eLlTfKHAkE0hpVsNGiFYZh3eDtaqSg4EM2RrIumjpHwiAmUfoaf64JEuTScso4LpYsiYSEklR7tCuAfCIt9/mejp4ACxF76HyBxKbO0Tbf1qmFL+UiRmXrSGs01j4CgxPlABDVShE8L8qhnz2Q+sWg4/qEwM1qFpg4QEeM2zAQx6tt2cVY8XkqifK6B6/2XgwEfdnpk7ZsmCnOiifmNYUQ94DDXQkBoC25r3VGhc32sPHNCQX5/AyY3C4bBp891lrJxqd6pWZ6NDJRmKvnVcP8=

services:
  - xvfb
  - docker

matrix:
  include:
    - if: type = push
      env: PROFILES="-Pjacoco"
    - if: type = cron
      env: PROFILES="-Pjacoco,mutation-testing"
      
script:
- mvn -f com.riccardomalavolti.apps.todolist/pom.xml clean verify $PROFILES jacoco:report coveralls:report sonar:sonar
