version: "3.7"
services:
    jenkins:
        build: 
            context: ./
            dockerfile: ./docker-files/jenkins.dockerfile
        image: riccardomalavolti/jenkins-opjdk8-mvn363
        env_file:
            - variables.env
        environment:
            DOCKER_SOCKET: /var/run/docker.sock
            DOCKER_HOST: unix://var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: "host"
