pipeline{
    agent any
    tools {
        maven 'maven-3.6.3'
        jdk 'jdk8'
    }

    stages{
        stage('Build'){
            steps {
                echo 'Build started'
                sh 'mvn -f com.riccardomalavolti.apps.todolist/pom.xml clean'
                sh "mvn -f com.riccardomalavolti.apps.todolist/pom.xml compile jacoco:prepare-agent"
                echo '======= Build finished ======='
                }
        }
        stage('Testing'){
            steps{
                echo 'Testing started'
                sh 'export DISPLAY=33'
                wrap([$class: 'Xvfb', additionalOptions: '', assignedLabels: '', autoDisplayName: true, debug: true, displayNameOffset: 33, screen: '1366x768x16']){
                    sh 'mvn -f com.riccardomalavolti.apps.todolist/pom.xml verify -Pjacoco,mutation-testing jacoco:report surefire-report:report-only surefire-report:failsafe-report-only org.apache.maven.plugins:maven-site-plugin:3.7.1:site -DgenerateReports=false'
                    junit 'com.riccardomalavolti.apps.todolist/target/*/*.xml'
                    jacoco()
                }
                echo 'Ending testing phase'
            }
        }

        stage('Verifing'){
            steps{
                echo 'Code quality analysis started'
                sh 'mvn -f ./com.riccardomalavolti.apps.todolist/pom.xml coveralls:report sonar:sonar'
                echo 'Code analysis ended.'
            }
        }
    }
}
