pipeline{
    agent any
    tools {
        maven 'Maven 3.6.3'
        jdk 'jdk8'
    }

    environment{
	COVERALLS_REPO_TOKEN = credentials('coveralls-repo-token')
	SONARCLOUD_TOKEN = credentials('sonarcloud-token')

    }

    stages{
        stage('Build'){
            steps {
                echo 'Build started'
                sh 'mvn -f com.riccardomalavolti.apps.todolist/pom.xml clean jacoco:prepare-agent'
                sh "mvn -f com.riccardomalavolti.apps.todolist/pom.xml compile"
                echo '======= Build finished ======='
                }
        }
	stage('Testing'){
	   steps{
		echo 'Testing started'
        	sh 'mvn -f com.riccardomalavolti.apps.todolist/pom.xml clean test -Pjacoco,mutation-testing jacoco:report coveralls:report'
		junit 'com.riccardomalavolti.apps.todolist/target/surefire-reports/*.xml'
		junit 'com.riccardomalavolti.apps.todolist/target/site/jacoco/*.xml'
		echo 'Ending testing phase'
	   }
	}
	stage('Verifing'){
	    steps{
		echo 'Code quality analysis started'
		sh 'mvn -f ./com.riccardomalavolti.apps.todolist/pom.xml verify -Pjacoco sonar:sonar'
		junit 'com.riccardomalavolti.apps.todolist/target/site/jacoco/*.xml'
		echo 'Code analysis ended.'
	   }
	}
    }
}
