pipeline{
    agent any
    tools {
        maven 'maven-3.6.3'
        jdk 'jdk8'
    }

    stages{
        stage('Build'){
            steps {
                echo 'Build started'
                sh 'mvn -f com.riccardomalavolti.apps.todolist/pom.xml clean'
                sh "mvn -f com.riccardomalavolti.apps.todolist/pom.xml compile jacoco:prepare-agent"
                echo '======= Build finished ======='
                }
        }
	stage('Testing'){
	   steps{
		echo 'Testing started'
                wrap([$class: 'Xvnc', takeScreenshot: false, useXauthority: true]) {
                    sh 'mvn -f com.riccardomalavolti.apps.todolist/pom.xml test -Pjacoco,mutation-testing jacoco:report coveralls:report'
		    junit 'com.riccardomalavolti.apps.todolist/target/*/*.xml'
		    jacoco()
                }
		echo 'Ending testing phase'
	   }
	}

	stage('Verifing'){
	    steps{
		echo 'Code quality analysis started'
		sh 'mvn -f ./com.riccardomalavolti.apps.todolist/pom.xml verify -Pjacoco sonar:sonar'
		echo 'Code analysis ended.'
	   }
	}
    }
}
